site_name: Ternary Computer (T27)
site_url: https://dasaelektronik.github.io/T27/
repo_url: https://github.com/DASAElektronik/T27
repo_name: DASAElektronik/T27
edit_uri: edit/master/docs/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.tracking
    - content.code.copy
    - search.suggest
    - search.highlight
    - header.autohide
  logo: assets/t27_logo.svg
  favicon: assets/t27_favicon.png

nav:
  - Home: index.md
  - Guide:
      - Quickstart: guide/quickstart.md
      - Contributing: guide/contributing.md
      - Licensing: guide/licensing.md
      - Governance: guide/governance.md
  - Design:
      - Architecture: design/architecture.md
      - Cells & Encoding: design/cells.md
      - Non-Infringement Scope: design/ip-scope.md
  - Reproducibility:
      - Tooling & Versions: repro/tooling.md
      - Tests & CI: repro/tests-ci.md
  - Roadmap: roadmap.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DASAElektronik/T27
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/daniel-schuch-a710418b/
