name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report!
  - type: input
    id: version
    attributes:
      label: Version / Commit
      description: The version or commit hash you are using
      placeholder: e.g. v0.1.0 or abcdef1
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Provide a minimal example if possible
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, tool versions, EDA versions, simulator, etc.
