# SPDX-License-Identifier: MIT
function(t27_enable_coverage target)
  if(MSVC OR NOT CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    message(FATAL_ERROR "Coverage requires GCC or Clang")
  endif()
  if(T27_ENABLE_LLVM_COVERAGE)
    if(NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
      message(FATAL_ERROR "LLVM source coverage requires Clang")
    endif()
    target_compile_options(${target} PRIVATE -fprofile-instr-generate -fcoverage-mapping)
    target_link_options(${target} PUBLIC -fprofile-instr-generate)
  else()
    target_compile_options(${target} PRIVATE --coverage)
    target_link_options(${target} PUBLIC --coverage)
  endif()
endfunction()
