# SPDX-License-Identifier: MIT
set(CPACK_PACKAGE_NAME t27)
set(CPACK_PACKAGE_VENDOR "T27 contributors")
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "T27 balanced-ternary core")
set(CPACK_GENERATOR ZIP)
set(CPACK_PACKAGE_FILE_NAME "t27-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
include(CPack)
